---
 - name: Cleanup both cv and tomcat service logs from the CV server
   #hosts: CRON_DEPLOY
   hosts: CV_LCL
   gather_facts: true
   become: true
   vars:
     OLD_LOG_DIR: "/opt/oldlogdir"
     CRON_HOURLY_DIR: "/etc/cron.hourly"
     CRON_DAILY_DIR: "/etc/cron.daily"
     CRON_WEEKLY_DIR: "/etc/cron.weekly"
   tasks:
   - name: Clean the cron job scripts
     file:
       path: "{{ item }}"
       state: absent
     with_items:
       - "{{ CRON_HOURLY_DIR }}/cv10_clearlog.sh"
       - "{{ CRON_HOURLY_DIR }}/cv9_clearlog.sh"
       - "{{ CRON_HOURLY_DIR }}/cv10_axiom_home_clearlog.sh"
       - "{{ CRON_HOURLY_DIR }}/cv9_axiom_home_clearlog.sh"
       - "{{ CRON_HOURLY_DIR }}/tomcat_clearlog.sh"
       - "{{ CRON_WEEKLY_DIR }}/catalina_truncate.sh"
       - "{{ CRON_HOURLY_DIR }}/cv10_tmp_clear.sh"
       - "{{ CRON_HOURLY_DIR }}/cv9_tmp_clear.sh"
       - "{{ CRON_HOURLY_DIR }}/axiom_project_file_clean.sh"
       - "{{ CRON_HOURLY_DIR }}/cron_tomcat_tmp_clear.sh"
       - "{{ CRON_HOURLY_DIR }}/cron_tomcat_uikit_tmp_clear.sh"
       - "{{ CRON_HOURLY_DIR }}/cv10_delete_svrlog_back_file.sh"
       - "{{ CRON_HOURLY_DIR }}/cv9_delete_svrlog_back_file.sh"

   - name: Delete Old log directory
     file:
       path: "{{ OLD_LOG_DIR }}"
       state: absent

   - name: Restart Crond service
     service:
       name: crond.service
       state: restarted

